# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubechat" do
  def caveats
    <<~EOS
      \e[1mTo run kubechat cli simply run:\e[0m
        \e[32mkubechat\e[0m

      \e[1mTo run kubechat on specific ip and port:\e[0m
        \e[32mkubechat --listen :7080\e[0m
    EOS
  end

  name "kubechat"
  desc "kubechat is a single binary to manage multiple clusters."
  homepage "https://github.com/pramodksahoo/kubechat"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubechat"

  on_macos do
    url "https://github.com/pramodksahoo/kubechat/releases/download/v#{version}/kubechat_Darwin_all.tar.gz"
    sha256 "bd8a34a94ead117b64c8f262903d5763771b1187bde1ee0615bc8b4bf57aa213"
  end

  on_linux do
    on_intel do
      url "https://github.com/pramodksahoo/kubechat/releases/download/v#{version}/kubechat_Linux_x86_64.tar.gz"
      sha256 "c59cb2d4c9b4359c4dd8bca95a46f11f2140e98f68ceb81417ca609923989c23"
    end
    on_arm do
      url "https://github.com/pramodksahoo/kubechat/releases/download/v#{version}/kubechat_Linux_arm64.tar.gz"
      sha256 "18d68cac17b047d50a519c3f5f37a3eb84a14c8898af9c1b77878a2210b7655b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubechat"]
    end
  end

  # No zap stanza required
end
